### ISSUE TITLE
濃厚豚骨豚無双さんの濃厚無双ラーメンがありません

### ISSUE THREAD

**Issue by mi171320** [mi171335/git-test#1]
どうにかしてください

**Comment by mi171333** [comment]
どうしてくれるんですか

**Comment by mi171335** [comment]
こちらが　濃厚とんこつ豚無双さんの
濃厚無双ラーメン　海苔トッピングです

# **うっひょ～～～～～～！**

着席時　コップに水垢が付いていたのを見て
大きな声を出したら　店主さんからの誠意で
チャーシューをサービスしてもらいました
俺の動画次第でこの店潰すことだって出来るんだぞってことで
いただきま～～～～す！まずはスープから
# コラ～！
これでもかって位ドロドロの濃厚スープの中には
虫が入っており　怒りのあまり
卓上調味料を全部倒してしまいました～！
すっかり店側も立場を弁え　誠意のチャーシュー丼を貰った所で
お次に　圧倒的存在感の極太麺を
## 啜る～！
# 殺すぞ～！
ワシワシとした触感の麺の中には、髪の毛が入っており
さすがのSUSURUも　厨房に入って行ってしまいました～！
###### ちなみに、店主さんが土下座している様子は　ぜひサブチャンネルを御覧ください

**Comment by mi171333** [comment]
感動しました…😭😭😭😭😭

**Comment by mi171320** [comment]
良い文章

**Comment by mi171320** [comment]
ありがとうございます

**Comment by wakimiko01000010** [comment]
くそ過疎うしえIssue

**Comment by isataku** [comment]
本件は再度Openするべきです
